# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureAppConfiguration@5
  inputs:
    azureSubscription: 'azsub-lz-sponsorship(f124b668-7e3d-4b53-ba80-09c364def1f3)'
    AppConfigurationEndpoint: 'https://azappconfiguration-sponsor.azconfig.io'
    KeyFilter: 'DevOps:*'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Write-Host "$(DevOps:Config:DemoValue)"'
