name: "Sync Configuration"
description: "Composite actions of syncing configurations"
inputs:
  appsetting-file:
    description: 'Application setting file'
    required: true
  secret-file:
      description: 'Application secret file'
      required: true
  appsetting-label:
    description: 'Label for the app setting'
    required: true
  connectionstring:
    description: 'The connectionstring for app configuration'
    required: true
    secret: true
runs:
  using: "composite"
  steps:
    - uses: azure/appconfiguration-sync@v1 
      with: 
        configurationFile: '${{inputs.appsetting-file}}' 
        format: 'json' 
        connectionString: ${{ inputs.connectionstring }} 
        separator: ':' 
        label: '${{inputs.appsetting-label}}'
    - uses: azure/appconfiguration-sync@v1
      with:
        configurationFile: '${{inputs.secrets-file}}'
        format: 'json'
        connectionString: ${{ inputs.connectionstring }}
        separator: ':'
        label: '${{inputs.appsetting-label}}'
        contentType: 'application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8'