name: "Sync Configuration"
description: "Composite actions of syncing configurations"
inputs:
  appsetting-file:
    description: 'Application setting file'
    required: true
  secret-file:
      description: 'Application secret file'
      required: false
  appsetting-label:
    description: 'Label for the app setting'
    required: false
  connectionstring:
    description: 'The connectionstring for app configuration'
    required: true
    secret: true
runs:
  using: "composite"
  steps:
    - uses: azure/appconfiguration-sync@v1 
      if: ${{ inputs.appsetting-label != '' }}
      with: 
        configurationFile: '${{inputs.appsetting-file}}' 
        format: 'json' 
        connectionString: ${{ inputs.connectionstring }} 
        separator: ':' 
        label: '${{ inputs.appsetting-label }} '
    - uses: azure/appconfiguration-sync@v1 
      if: ${{ inputs.appsetting-label == '' }}
      with: 
        configurationFile: '${{inputs.appsetting-file}}' 
        format: 'json' 
        connectionString: ${{ inputs.connectionstring }} 
        separator: ':' 
    - uses: azure/appconfiguration-sync@v1
      if: ${{ inputs.secret-file != '' && inputs.appsetting-label != '' }}
      with:
        configurationFile: '${{inputs.secret-file}}'
        format: 'json'
        connectionString: ${{ inputs.connectionstring }}
        separator: ':'
        contentType: 'application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8'
        label: '${{inputs.appsetting-label}}'
    - uses: azure/appconfiguration-sync@v1
      if: ${{ inputs.secret-file != '' && inputs.appsetting-label == '' }}
      with:
        configurationFile: '${{inputs.secret-file}}'
        format: 'json'
        connectionString: ${{ inputs.connectionstring }}
        separator: ':'
        contentType: 'application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8'