# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureAppConfiguration@5
  displayName: Get Azure App Configurations
  inputs:
    azureSubscription: 'azsub-lz-sponsorship(f124b668-7e3d-4b53-ba80-09c364def1f3)'
    AppConfigurationEndpoint: 'https://azappconfig-sponsor.azconfig.io'
    KeyFilter: 'DevOps:*'
- task: PowerShell@2
  displayName: Display values from App Configuration
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Regular value: $(DevOps:Config:DemoValue)"
      Write-Host "Secret value: $(DevOps:Secret:DevOpsSecret)"
