name: Configuration Sync

on:
  push:
    branches: [ "main" ]
    paths:
      - "configuration/**"
      - "secrets/**"

jobs:

  syncconfig: 
    name: 'Sync development configuration'
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v1 
      - id: syncconfigitems
        uses: ./.github/actions/syncconfigitems
        with:
          appsetting-file: 'configuration/appsettings.dev.json' 
          secret-file: 'secrets/appsettings.secrets.dev.json'
          appsetting-label: 'Development'