name: Configuration Sync

on:
  push:
    branches: [ "main" ]
    paths:
      - "configuration/**"

jobs:

  syncconfig: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v1 
      - uses: azure/appconfiguration-sync@v1 
        with: 
          configurationFile: 'configuration/appsettings.dev.json' 
          format: 'json' 
          connectionString: ${{ secrets.APPCONFIG }} 
          separator: ':' 
          strict: true 
          label: 'Development'
